# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "32922c7002a68a1ea720ba1e253af430"
name = "variantis-app"
application_url = "https://variantis-app-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_themes,write_themes,read_inventory,write_inventory"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://variantis-app-production.up.railway.app/auth/callback" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
