api_version = "2026-07"
uid = "0290412e-1f0d-3f96-9041-98759ee22fb13793ceda"

[[extensions]]
type = "theme"
name = "Variantis"
handle = "variantis-theme"

  [extensions.development]
    resource = {url = "/products/example"}
    preview_url = "/products/example"
