api_version = "2026-07"

[[extensions]]
type = "theme"
name = "Variantis"
handle = "variantis-theme"

  [extensions.development]
    resource = {url = "/products/example"}
    preview_url = "/products/example"
