api_version = "2026-07"
uid = "da1c1830-872e-6ee6-6ee2-2903f1b091e602c3c76e"

[[extensions]]
type = "theme"
name = "Variantis – Collection Display"
handle = "variantis-collection"

  [extensions.development]
    resource = {url = "/collections/all"}
    preview_url = "/collections/all"
